//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 11/08/2010 9:59:32 PM
namespace ChartisClient.ChartisService
{
    
    /// <summary>
    /// There are no comments for Repository in the schema.
    /// </summary>
    public partial class Repository : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Repository object.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Repository(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("ChartisDomain", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("ChartisClient.ChartisService", typeName.Substring(13)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("ChartisClient.ChartisService", global::System.StringComparison.Ordinal))
            {
                return string.Concat("ChartisDomain.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Sprints in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Sprint> Sprints
        {
            get
            {
                if ((this._Sprints == null))
                {
                    this._Sprints = base.CreateQuery<Sprint>("Sprints");
                }
                return this._Sprints;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Sprint> _Sprints;
        /// <summary>
        /// There are no comments for Stories in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Story> Stories
        {
            get
            {
                if ((this._Stories == null))
                {
                    this._Stories = base.CreateQuery<Story>("Stories");
                }
                return this._Stories;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Story> _Stories;
        /// <summary>
        /// There are no comments for Sprints in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSprints(Sprint sprint)
        {
            base.AddObject("Sprints", sprint);
        }
        /// <summary>
        /// There are no comments for Stories in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToStories(Story story)
        {
            base.AddObject("Stories", story);
        }
    }
    /// <summary>
    /// There are no comments for ChartisDomain.Sprint in the schema.
    /// </summary>
    /// <KeyProperties>
    /// SprintId
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Sprints")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("SprintId")]
    public partial class Sprint : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Sprint object.
        /// </summary>
        /// <param name="sprintId">Initial value of SprintId.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Sprint CreateSprint(int sprintId)
        {
            Sprint sprint = new Sprint();
            sprint.SprintId = sprintId;
            return sprint;
        }
        /// <summary>
        /// There are no comments for Property SprintId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int SprintId
        {
            get
            {
                return this._SprintId;
            }
            set
            {
                this.OnSprintIdChanging(value);
                this._SprintId = value;
                this.OnSprintIdChanged();
                this.OnPropertyChanged("SprintId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _SprintId;
        partial void OnSprintIdChanging(int value);
        partial void OnSprintIdChanged();
        /// <summary>
        /// There are no comments for Property Goal in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Goal
        {
            get
            {
                return this._Goal;
            }
            set
            {
                this.OnGoalChanging(value);
                this._Goal = value;
                this.OnGoalChanged();
                this.OnPropertyChanged("Goal");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Goal;
        partial void OnGoalChanging(string value);
        partial void OnGoalChanged();
        /// <summary>
        /// There are no comments for Stories in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Story> Stories
        {
            get
            {
                return this._Stories;
            }
            set
            {
                this._Stories = value;
                this.OnPropertyChanged("Stories");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Story> _Stories = new global::System.Data.Services.Client.DataServiceCollection<Story>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ChartisDomain.Story in the schema.
    /// </summary>
    /// <KeyProperties>
    /// StoryId
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Stories")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("StoryId")]
    public partial class Story : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Story object.
        /// </summary>
        /// <param name="storyId">Initial value of StoryId.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Story CreateStory(int storyId)
        {
            Story story = new Story();
            story.StoryId = storyId;
            return story;
        }
        /// <summary>
        /// There are no comments for Property StoryId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int StoryId
        {
            get
            {
                return this._StoryId;
            }
            set
            {
                this.OnStoryIdChanging(value);
                this._StoryId = value;
                this.OnStoryIdChanged();
                this.OnPropertyChanged("StoryId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _StoryId;
        partial void OnStoryIdChanging(int value);
        partial void OnStoryIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Notes in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Notes
        {
            get
            {
                return this._Notes;
            }
            set
            {
                this.OnNotesChanging(value);
                this._Notes = value;
                this.OnNotesChanged();
                this.OnPropertyChanged("Notes");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Notes;
        partial void OnNotesChanging(string value);
        partial void OnNotesChanged();
        /// <summary>
        /// There are no comments for Sprint in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Sprint Sprint
        {
            get
            {
                return this._Sprint;
            }
            set
            {
                this._Sprint = value;
                this.OnPropertyChanged("Sprint");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Sprint _Sprint;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
